version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "super-awesome/circleci.yml"
          command: "echo very cool"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello